# Generated by Django 5.2.15 on 2026-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='active_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
