# Generated by Django 5.2.15 on 2026-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
